"""
Data models for Pinpo (AI-Powered Deposition Topic Index).
Defines schemas for canonical transcript lines, topic entries, and complete indices.

All models use Pydantic BaseModel for automatic validation, JSON serialization,
and schema enforcement. This is the single source of truth for all data structures
used across the pipeline.
"""

# =========================================================================
# [BLOCK-00: Data Model Definitions — Pydantic Schemas]
# WHY: Every module in the pipeline (parser, chunker, segmenter, validator,
#      merger, omission detector, exporter) operates on these shared data
#      models. Using Pydantic ensures type safety, automatic JSON
#      serialization (.model_dump()), and self-documenting Field descriptions.
# HOW: Each class inherits from BaseModel. Fields use Field(...) for required
#      values and Field(default=X) for optional values with defaults.
# WHERE USED: Imported by every module in src/ and scripts/
# =========================================================================

from typing import List, Optional, Dict, Any
from pydantic import BaseModel, Field  # Pydantic v2 — BaseModel provides validation + serialization


# =========================================================================
# [BLOCK-00A: TranscriptLine — Atomic Line Model]
# WHAT: Represents ONE line of deposition testimony with its exact
#       (page, line) coordinate. This is the fundamental unit of the
#       entire pipeline — every transcript line parsed from the PDF
#       becomes a TranscriptLine object.
# WHY: Enables O(1) coordinate lookup, ensures zero dropped lines,
#      and provides the ground truth that the validator checks against.
# =========================================================================
class TranscriptLine(BaseModel):
    """Represents an atomic, canonically addressed line in a deposition transcript."""

    # global_line_id: Sequential counter (1, 2, 3, ..., N) across all pages
    # Used for ordering and range queries without page arithmetic
    global_line_id: int = Field(..., description="Unique sequential line index across the entire transcript (1..N)")

    # page: The PRINTED page number from the court reporter transcript (e.g., 7..88)
    # NOT the PDF page index — the printed footer number is used for legal citation accuracy
    page: int = Field(..., description="Official printed transcript page number (e.g., 7..88)")

    # line: Line number on the page (1..25). Court reporters use a standard 25-line page grid
    line: int = Field(..., description="Line number on the page (typically 1..25)")

    # speaker: Identified speaker tag (e.g., "QUESTION (PURCELL)", "ANSWER (YU)", "THE WITNESS")
    # Empty string for continuation lines (speaker carries over from previous line)
    speaker: str = Field(default="", description="Identified speaker (e.g., 'Q', 'A', 'MR. PURCELL', 'THE WITNESS')")

    # text: The cleaned spoken content, stripped of line numbers and timestamps
    # This is what the LLM sees and what the validator matches quotes against
    text: str = Field(..., description="Cleaned spoken text for the line, stripped of line numbers & timestamps")

    # timestamp: Video deposition timestamp if present (e.g., "01:17")
    # Optional because not all lines have timestamps — only speaker turns
    timestamp: Optional[str] = Field(default=None, description="Recorded video timestamp (e.g., '01:17')")

    # raw_text: The original unmodified line string as extracted from the PDF
    # Preserved for debugging and audit trail — never modified after creation
    raw_text: str = Field(default="", description="Original raw line string as extracted from source")

    @property
    def coordinate(self) -> str:
        """Formatted coordinate string, e.g., 'Page 12, Line 4'.
        Used in human-readable output like HTML and Markdown reports."""
        return f"Page {self.page}, Line {self.line}"


# =========================================================================
# [BLOCK-00B: TopicEntry — Verified Topic Segment Model]
# WHAT: Represents a single topic segment in the deposition (e.g.,
#       "Educational Background & Degrees" spanning P08:L01 to P12:L15).
# WHY: This is the core output of the LLM segmentation step, and gets
#      enriched by the validator with confidence scores and verification flags.
# KEY DESIGN: The `needs_human_review` field implements the BINARY TRUST MODEL
#             demanded by the interviewer — either 100% verified or flagged.
# =========================================================================
class TopicEntry(BaseModel):
    """Represents a verified, chronologically ordered topic segment in the transcript."""

    # topic: Concise legal topic title generated by the LLM
    # Examples: "Employment History", "Loan Servicing Transfer", "Ground Rules & Admonitions"
    topic: str = Field(..., description="Concise, attorney-friendly topic label (e.g., 'Employment History')")

    # Coordinate bounds: start_page/start_line to end_page/end_line
    # These define the exact range of transcript lines this topic covers
    start_page: int = Field(..., description="Starting printed page number")
    start_line: int = Field(..., description="Starting line number (1..25)")
    end_page: int = Field(..., description="Ending printed page number")
    end_line: int = Field(..., description="Ending line number (1..25)")

    # Global IDs: Set by the validator after snapping to verified coordinates
    # Used for efficient range queries without page/line arithmetic
    start_global_id: Optional[int] = Field(default=None, description="Starting global sequential line ID")
    end_global_id: Optional[int] = Field(default=None, description="Ending global sequential line ID")

    # summary: LLM-generated 1-2 sentence factual summary of testimony in this segment
    summary: str = Field(default="", description="Brief factual summary of testimony within this segment")

    # supporting_quote: Verbatim quote from the transcript that anchors this topic
    # The validator uses this to locate the topic in the ground truth transcript
    supporting_quote: str = Field(default="", description="Verbatim quote from the transcript anchoring this topic")

    # confidence: Binary trust score — 1.0 (all 4 pillars pass) or 0.0 (any pillar fails)
    # INTERVIEWER REQUIREMENT: No intermediate confidence scores like 85% or 60%
    confidence: float = Field(default=1.0, description="Confidence/validation score (0.0 to 1.0)")

    # verified: True if both start and end coordinates were found in the canonical transcript
    verified: bool = Field(default=False, description="Whether start and end lines were deterministically verified against raw transcript")

    # needs_human_review: BINARY TRUST MODEL flag
    # True = at least one of the 4 validation pillars failed → lawyer must verify
    # False = ALL 4 pillars passed → fully machine-verified, no human intervention needed
    needs_human_review: bool = Field(default=True, description="Flag for human verification — True unless ALL 4 validation pillars pass at 100%")

    @property
    def start_coordinate(self) -> str:
        """Human-readable start coordinate, e.g., 'Page 8, Line 1'."""
        return f"Page {self.start_page}, Line {self.start_line}"

    @property
    def end_coordinate(self) -> str:
        """Human-readable end coordinate, e.g., 'Page 12, Line 15'."""
        return f"Page {self.end_page}, Line {self.end_line}"


# =========================================================================
# [BLOCK-00C: TopicIndex — Complete Deposition Index Model]
# WHAT: The top-level container holding all topics for one deposition,
#       plus metadata about the witness, case, and pipeline run.
# WHY: This is the final output of the pipeline — serialized to JSON,
#      Markdown, and HTML by the exporter. Also consumed by the web viewer.
# =========================================================================
class TopicIndex(BaseModel):
    """Complete structured Topic Index representing the entire deposition."""

    # Deposition-level metadata
    title: str = Field(default="Deposition Topic Index", description="Title of the deposition index")
    witness: str = Field(default="Persis Yu", description="Name of the deponent / witness")
    date: Optional[str] = Field(default=None, description="Date of the deposition")
    case_name: Optional[str] = Field(default=None, description="Case / matter name")

    # Processing stats
    total_pages: int = Field(..., description="Total pages processed")
    total_lines: int = Field(..., description="Total substantive lines processed")

    # The main payload: ordered list of all topic segments
    topics: List[TopicEntry] = Field(default_factory=list, description="List of chronologically ordered topic entries")

    # Pipeline configuration and runtime metadata (source PDF, coverage %, model used, etc.)
    metadata: Dict[str, Any] = Field(default_factory=dict, description="Pipeline configuration, timestamps, model parameters")
